### ISSUE TITLE
getRandomID is slow

### ISSUE THREAD

**Issue by saltybeagle** [unl/GoURL#1]
When the system approaches the limit of aliases permitted by the configured alias length, finding a random id takes longer and longer. This can cause timeout issues, and there is no notification when the system is out of IDs.

getRandomID() should be improved to return a random ID faster, and notify the end-user or admins that the available character space has been used up.

**Comment by jsturek** [comment]
Some concerns addressed with https://github.com/unl/GoURL/pull/39
