### ISSUE TITLE
Feature Request: Allow in-place editing of your own URLs without deleting and re-creating 

### ISSUE THREAD

**Issue by mwolff-unl** [unl/GoURL#23]
It would be neat to allow for the editing of your own URLs. You can do this anyway by deleting and re-creating the Go URL, but that isn't apparent on the website. At least, it isn't apparent you can get the same Go URL back after deleting one. Adding documentation/instruction for that workaround might work too.

**Comment by jsturek** [comment]
Adding editing in https://github.com/unl/GoURL/pull/35
