### ISSUE TITLE
Dont load every QR Code image file on page load

### ISSUE THREAD

**Issue by ericras** [unl/GoURL#89]
With data tables the "Your URLs" page loads every one of your links, and the QR codes are loaded for every link.  Thus you can have hundreds of images load and slows the page down.  

Either:

- easy: change the QR codes from visibly shown <img> to just links to the image file
- harder: make the content of the QR code modal load via ajax

**Comment by tommyneu** [comment]
I will probably make that whole modal be generated when that button is clicked. So it will only load the images when the "QR Code" button is clicked and that modal is created.
